services:
  db:
    build: .
    container_name: VolcaAPIDB
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: VolcAPIDB
    ports:
      - "5432:5432"
    volumes:
      - volcAPIdb:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  volcAPIdb:
    external: true